export interface Resource {
  id: string
  name: string
  category: 'food' | 'shelter' | 'health' | 'education' | 'community' | 'youth' | 'seniors' | 'employment'
  description: string
  address: string
  phone: string
  email: string
  website: string
  hours: string
  services: string[]
  image: string
  coordinates: [number, number]
  featured?: boolean
}

export const categories = [
  { id: 'food', label: 'Food & Nutrition', icon: 'utensils', color: 'bg-terracotta' },
  { id: 'shelter', label: 'Housing & Shelter', icon: 'home', color: 'bg-chestnut' },
  { id: 'health', label: 'Health & Wellness', icon: 'heart', color: 'bg-sage' },
  { id: 'education', label: 'Education', icon: 'book', color: 'bg-honey' },
  { id: 'community', label: 'Community Centers', icon: 'users', color: 'bg-terracotta' },
  { id: 'youth', label: 'Youth Programs', icon: 'star', color: 'bg-sage' },
  { id: 'seniors', label: 'Senior Services', icon: 'heart', color: 'bg-honey' },
  { id: 'employment', label: 'Employment', icon: 'briefcase', color: 'bg-chestnut' },
] as const

export const resources: Resource[] = [
  {
    id: '1',
    name: 'Maplewood Community Food Bank',
    category: 'food',
    description: 'Providing nutritious food to families in need since 1985. Our warm volunteers ensure everyone leaves with a full basket and a fuller heart. We believe no neighbor should go hungry.',
    address: '245 Oak Street, Maplewood',
    phone: '(555) 234-5678',
    email: 'hello@maplewoodfoodbank.org',
    website: 'https://maplewoodfoodbank.org',
    hours: 'Mon-Fri: 9AM-5PM, Sat: 10AM-2PM',
    services: ['Food Distribution', 'Meal Programs', 'Nutrition Education', 'Emergency Food Boxes', 'Holiday Meal Kits'],
    image: '/images/food-bank.jpg',
    coordinates: [40.7128, -74.006],
    featured: true,
  },
  {
    id: '2',
    name: 'Riverside Community Center',
    category: 'community',
    description: 'The heart of our neighborhood! A gathering place for all ages featuring classes, events, and programs that bring our community together. Stop by for coffee and stay for friendship.',
    address: '180 River Road, Riverside',
    phone: '(555) 345-6789',
    email: 'info@riversidecc.org',
    website: 'https://riversidecc.org',
    hours: 'Mon-Sun: 8AM-9PM',
    services: ['Community Events', 'Meeting Rooms', 'Fitness Classes', 'Art Workshops', 'After-School Programs', 'Senior Activities'],
    image: '/images/community-center.jpg',
    coordinates: [40.7148, -74.008],
    featured: true,
  },
  {
    id: '3',
    name: 'Neighborhood Public Library',
    category: 'education',
    description: 'More than just books! Our cozy library offers free WiFi, computer access, children\'s story time, and a warm reading nook perfect for rainy days. Your second living room awaits.',
    address: '320 Elm Avenue, Downtown',
    phone: '(555) 456-7890',
    email: 'library@neighborhood.gov',
    website: 'https://neighborhoodlibrary.org',
    hours: 'Mon-Thu: 10AM-8PM, Fri-Sat: 10AM-5PM, Sun: 1PM-5PM',
    services: ['Book Lending', 'Computer Access', 'Story Time', 'Tutoring Programs', 'ESL Classes', 'Job Search Help'],
    image: '/images/library.jpg',
    coordinates: [40.7108, -74.004],
    featured: true,
  },
  {
    id: '4',
    name: 'Hope Haven Shelter',
    category: 'shelter',
    description: 'Providing safe, warm beds and supportive services to those experiencing homelessness. Our dedicated team helps residents get back on their feet with dignity and compassion.',
    address: '78 Maple Lane, Westside',
    phone: '(555) 567-8901',
    email: 'intake@hopehaven.org',
    website: 'https://hopehaven.org',
    hours: 'Open 24/7 for emergencies',
    services: ['Emergency Shelter', 'Transitional Housing', 'Case Management', 'Job Training', 'Mental Health Support'],
    image: '/images/shelter.jpg',
    coordinates: [40.7168, -74.012],
  },
  {
    id: '5',
    name: 'Sunshine Community Garden',
    category: 'community',
    description: 'Grow your own vegetables and flowers while making lifelong friends! Our garden plots are available to all residents. Weekly workshops teach sustainable gardening practices.',
    address: '425 Garden Way, Eastside',
    phone: '(555) 678-9012',
    email: 'grow@sunshinegarden.org',
    website: 'https://sunshinegarden.org',
    hours: 'Dawn to Dusk, Daily',
    services: ['Garden Plots', 'Gardening Workshops', 'Seed Library', 'Composting Program', 'Kids\' Garden Club'],
    image: '/images/community-garden.jpg',
    coordinates: [40.7138, -74.002],
  },
  {
    id: '6',
    name: 'Caring Hands Health Clinic',
    category: 'health',
    description: 'Affordable healthcare for all! Our compassionate medical team provides primary care, dental services, and mental health support on a sliding scale. No one turned away.',
    address: '560 Health Plaza, Central',
    phone: '(555) 789-0123',
    email: 'appointments@caringhands.org',
    website: 'https://caringhands.org',
    hours: 'Mon-Fri: 8AM-6PM, Sat: 9AM-1PM',
    services: ['Primary Care', 'Dental Services', 'Mental Health', 'Vaccination Clinics', 'Health Education', 'Prescription Assistance'],
    image: '/images/health-clinic.jpg',
    coordinates: [40.7118, -74.009],
  },
  {
    id: '7',
    name: 'Bright Futures Youth Center',
    category: 'youth',
    description: 'Where young people discover their potential! Safe after-school environment with tutoring, sports, arts, and mentorship. Every child deserves a bright future.',
    address: '890 Youth Avenue, Northside',
    phone: '(555) 890-1234',
    email: 'hello@brightfutures.org',
    website: 'https://brightfutures.org',
    hours: 'Mon-Fri: 3PM-8PM, Sat: 10AM-4PM',
    services: ['After-School Programs', 'Tutoring', 'Sports Leagues', 'Art Classes', 'Summer Camp', 'College Prep'],
    image: '/images/youth-center.jpg',
    coordinates: [40.7188, -74.005],
  },
  {
    id: '8',
    name: 'Golden Years Senior Center',
    category: 'seniors',
    description: 'A warm community for our beloved seniors! Daily activities, hot meals, health screenings, and wonderful companionship. Because our elders deserve to thrive.',
    address: '215 Senior Lane, Southside',
    phone: '(555) 901-2345',
    email: 'welcome@goldenyears.org',
    website: 'https://goldenyears.org',
    hours: 'Mon-Fri: 9AM-5PM',
    services: ['Daily Meals', 'Social Activities', 'Health Screenings', 'Transportation', 'Computer Classes', 'Exercise Programs'],
    image: '/images/senior-center.jpg',
    coordinates: [40.7088, -74.007],
  },
  {
    id: '9',
    name: 'Community Job Connect',
    category: 'employment',
    description: 'Helping neighbors find meaningful employment! Resume workshops, interview coaching, job fairs, and connections to local employers who care about our community.',
    address: '345 Commerce Street, Business District',
    phone: '(555) 012-3456',
    email: 'jobs@communityjobconnect.org',
    website: 'https://communityjobconnect.org',
    hours: 'Mon-Fri: 9AM-5PM',
    services: ['Job Listings', 'Resume Help', 'Interview Coaching', 'Skills Training', 'Career Counseling', 'Job Fairs'],
    image: '/images/community-center.jpg',
    coordinates: [40.7158, -74.003],
  },
  {
    id: '10',
    name: 'Little Hands Childcare Co-op',
    category: 'youth',
    description: 'Affordable, loving childcare run by and for our community. Parent cooperative model ensures high quality care with reasonable costs. Your little ones are in good hands.',
    address: '167 Family Circle, Eastside',
    phone: '(555) 123-4567',
    email: 'enroll@littlehands.org',
    website: 'https://littlehands.org',
    hours: 'Mon-Fri: 7AM-6PM',
    services: ['Infant Care', 'Toddler Programs', 'Preschool', 'Before/After School', 'Parent Education', 'Play Groups'],
    image: '/images/youth-center.jpg',
    coordinates: [40.7098, -74.001],
  },
]

export interface Event {
  id: string
  title: string
  date: string
  time: string
  location: string
  description: string
  category: string
  organizer: string
}

export const events: Event[] = [
  {
    id: '1',
    title: 'Community Potluck Dinner',
    date: '2026-04-05',
    time: '6:00 PM',
    location: 'Riverside Community Center',
    description: 'Bring your favorite dish and meet your neighbors! A wonderful evening of food, music, and community spirit.',
    category: 'Social',
    organizer: 'Riverside Community Center',
  },
  {
    id: '2',
    title: 'Spring Garden Workshop',
    date: '2026-04-08',
    time: '10:00 AM',
    location: 'Sunshine Community Garden',
    description: 'Learn how to start your spring garden! Seeds, soil, and snacks provided. All skill levels welcome.',
    category: 'Workshop',
    organizer: 'Sunshine Community Garden',
  },
  {
    id: '3',
    title: 'Job Fair for All',
    date: '2026-04-10',
    time: '9:00 AM - 3:00 PM',
    location: 'Community Job Connect',
    description: 'Meet local employers, get resume help, and find your next opportunity. Professional attire suggested.',
    category: 'Employment',
    organizer: 'Community Job Connect',
  },
  {
    id: '4',
    title: 'Kids Story Time',
    date: '2026-04-12',
    time: '11:00 AM',
    location: 'Neighborhood Public Library',
    description: 'Weekly story time for little ones ages 2-6. Songs, crafts, and new friends await!',
    category: 'Youth',
    organizer: 'Neighborhood Public Library',
  },
  {
    id: '5',
    title: 'Senior Bingo Night',
    date: '2026-04-14',
    time: '7:00 PM',
    location: 'Golden Years Senior Center',
    description: 'Join us for a fun evening of bingo! Prizes, refreshments, and great company. Free admission.',
    category: 'Seniors',
    organizer: 'Golden Years Senior Center',
  },
  {
    id: '6',
    title: 'Health & Wellness Fair',
    date: '2026-04-18',
    time: '10:00 AM - 2:00 PM',
    location: 'Caring Hands Health Clinic',
    description: 'Free health screenings, nutrition info, fitness demos, and more! Open to all community members.',
    category: 'Health',
    organizer: 'Caring Hands Health Clinic',
  },
  {
    id: '7',
    title: 'Youth Art Show',
    date: '2026-04-20',
    time: '4:00 PM',
    location: 'Bright Futures Youth Center',
    description: 'Celebrate our young artists! Student artwork on display with refreshments and live music.',
    category: 'Youth',
    organizer: 'Bright Futures Youth Center',
  },
  {
    id: '8',
    title: 'Community Clean-Up Day',
    date: '2026-04-22',
    time: '9:00 AM',
    location: 'Town Square',
    description: 'Earth Day special! Help beautify our neighborhood. Supplies provided, volunteers of all ages welcome.',
    category: 'Community',
    organizer: 'Neighborly Hub',
  },
  {
    id: '9',
    title: 'Food Drive Collection',
    date: '2026-04-25',
    time: '8:00 AM - 6:00 PM',
    location: 'Maplewood Community Food Bank',
    description: 'Drop off non-perishable items to help stock our pantry. Every can counts!',
    category: 'Food',
    organizer: 'Maplewood Community Food Bank',
  },
  {
    id: '10',
    title: 'Neighborhood Movie Night',
    date: '2026-04-28',
    time: '8:00 PM',
    location: 'Riverside Park',
    description: 'Outdoor movie under the stars! Bring blankets and chairs. Popcorn provided. Family-friendly film.',
    category: 'Social',
    organizer: 'Riverside Community Center',
  },
]
